apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-smtp4dev.fullname" . }}
  labels:
    {{- include "helm-smtp4dev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 25
      targetPort: smtp
      protocol: TCP
      name: smtp
    - port: 143
      targetPort: imap
      protocol: TCP
      name: imap
  selector:
    {{- include "helm-smtp4dev.selectorLabels" . | nindent 4 }}
