---
name: Helm Release

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Lint and Test Charts
    types:
      - completed
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: gha-runners
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Helm Release
        uses: imio/gha/helm-release-notify@v8 
        with:
          HELM_VERSION: '4.2.3'                      
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          TARGET_DIR: smtp4dev
          SIGNER_KEY: ${{ secrets.HELM_SIGNER_KEY }}
          SIGNER_KEY_ID: ${{ secrets.HELM_SIGNER_KEY_ID }}
          SIGNER_KEY_PASSPHRASE: ${{ secrets.HELM_SIGNER_KEY_PASSPHRASE }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
