name: Helm Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "helm-charts"
      - name: Publish Helm chart
        uses: tylerauerbeck/helm-gh-pages@main
        with:
          token: ${{ steps.app-token.outputs.token }}
          charts_dir: .
          index_dir: .
          charts_url: https://imio.github.io/helm-charts/
          owner: IMIO
          repository: helm-charts
          branch: gh-pages
          target_dir: smtp4dev