---
    name: Lint and Test Charts on PR
    
    on: [pull_request]
    
    jobs:
      lint-test:
        runs-on: self-hosted
        steps:
          - name: Lint and Test Charts
            uses: IMIO/gha/helm-test-notify@v3.9
            with:
              HELM_RELEASE: smtp4dev
              HELM_NAMESPACE: smtp4dev
              MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
    